### ISSUE TITLE
lfo example / hal reference?

### ISSUE THREAD

**Issue by ghost** [JordanAceto/stm32l0_mod_source#1]
would it be possible to get an example of a basic lfo or HAL as a resource for this?
would be super helpful for learning how to use all the pins ect
thanks!

**Comment by JordanAceto** [comment]
Hi there! Yes, this is a good idea. I have not added any examples mostly due to laziness. The way I typically use this board is to use it to try out some quick and dirty ideas to see if the L031 is sufficient for a project, and then port that code over to a project which has the same microcontroller on a larger board.

For example, these projects all use the same L031 uC (but not necessarily the same pinouts). I started development on this little breakout before committing to the "real" board:

- https://github.com/JordanAceto/whooshy_sound/tree/main/firmware
- https://github.com/JordanAceto/stereo_whooshy_sound/tree/master/firmware
- https://github.com/JordanAceto/msm_stereo_LPF/tree/main/firmware

Those projects all use the minimal CMSIS files and hand-rolled initialization code. I did it that way because I was in college at the time, and a big goal of the projects was educational value over efficiency. Today I would probably use CubeIDE for initialization and HAL functions, or maybe even use Rust.

Anyways, I'll see if I can whip something up to serve as an example or two. I am moving pretty slow on hobby projects atm, so it might not be right away.

Do you have an opinion on what format would be the most helpful? I think for starters I might do a basic CubeIDE project, this way people don't need to set up all the environment stuff on their own or mess with Makefiles/command line. I am going to assume that anyone interested in this has some experience with general STM32 development and can figure out how to set up the IDE/connect wires to the SWD port/etc.

Cheers and thanks for writing :)

**Comment by ghost** [comment]
that would be great, i have some experience with cube ide and c/c++ and basic command line but thought it would be super helpful to see how u call the dac on this board and general approach to the hal from a c/c++ perspective! thanks

**Comment by JordanAceto** [comment]
Hi there, I added an STM32CubeIDE project as a kind of hello-world for the board. It reads some pots and switches and outputs ramp waves on the two DAC channels. It's not much of a useful real-world project, but it hopefully gives you an idea of how you could read some pots and drive the DAC.
Let me know if this is in the ballpark of what you're looking for, suggestions (and pull requests!) are welcome.

**Comment by ghost** [comment]
thanks so much!

**Comment by JordanAceto** [comment]
Does that example give you enough to get started? If so we can close out this issue. It would be great to have more examples, but realistically I won't add more anytime soon. There are the three examples up in my earlier reply that could be pretty easily ported over to this board, these give you a "real LFO" with some nice features (multiple shapes, wave scan, set frequency directly).

**Comment by ghost** [comment]
oh no it helps alot, your initital examples also helped alot once i got stuck in, thanks alot
